import localStorageDataProvider from 'ra-data-local-storage';

const dataProvider = localStorageDataProvider({
    loggingEnabled: true,
    defaultData: {
        orarios: [
            {
                id: 1,
                orarioId: 1,
                codice: '0Q',
                breve: '',
                descrizione: 'Prova Quadro 8h',
                colore: '',
                tipologiaTipo: 'Elastico',
                tipologiaOreBase: '08:00',
                tipologiaOreMinime: '08:00',
                tipologiaGiornoDiSalvataggio: 'Entrata',
                timbratureDalle: '04:30',
                timbratureAlle: '19:00',
                timbratureGiorniSuccessiviPerTimbratura: 1,
                timbratureTimbratureSuPiuGiorni: true,
                timbratureCausaliFuoriIntervallo: false,
                orariSostitutiviSabato: '',
                orariSostitutiviDomenicaEFestivo: '',
                orariSostitutiviPreFestivo: '',
                segnalareTimbratureFuoriFasce: false,
                lavoroStraordinarioAutorizzato: true,
                lavoroStraordinarioArrotondamento: 'titolare',
                lavoroStraordinarioArrotondamentoSulleFasceDaAutorizzare: false,
                profilosId: 1,
                compensazioneCompensazioneSelettiva: false,
                compensazioneCumuloAssenze: '',
                compensazioneCumuloStraordinario: '',
                compensazioneMassimale: '00:00',
                compensazioneSaldoPositivo: false,
                compensazioneFasceSeAssenza: false,
                compensazionePauseNonRispettate: false,
                compensazioneDeduzioneAdattivaTimbratureTipo: false,
                compensazioneSequenzeEu: '',
                compensazioneTimbratureFuoriFasciaElastica: '',
                compensazioneSpostaTimbraturaTipo: '',
                compensazioneDisattivaFasceDopoIndividuaTipo: false,
                compensazioneOrarioRigido: false,
                postElaborazioniCompensazioneAutomatica: false,
                postElaborazioniVociAutomatiche: false,
                postElaborazioniUsaTipoReali: true,
                oreTeoricheHHTeoriche: 'minime',
                oreTeoricheTipoGG: 'lavorativo',
                strategieIgnorareTimbratureOrfane: false,
                strategieTimbratureDiscriminazioneAutomatica: false,
                strategieGiustificativiRigidi: true,
                strategieGiustificativiFlex: false,
                strategieGiustificativiAssenzaTimbrature: true,
                OmissioneDescrizioneOrdiniServizio: false
            },
            {
                id: 2,
                orarioId: 2,
                codice: '0Q7',
                breve: '',
                descrizione: 'Prova Quadro 7h',
                colore: '',
                tipologiaTipo: 'Elastico',
                tipologiaOreBase: '07:00',
                tipologiaOreMinime: '07:00',
                tipologiaGiornoDiSalvataggio: 'Entrata',
                timbratureDalle: '04:00',
                timbratureAlle: '',
                timbratureGiorniSuccessiviPerTimbratura: 0,
                timbratureTimbratureSuPiuGiorni: true,
                timbratureCausaliFuoriIntervallo: false,
                orariSostitutiviSabato: '',
                orariSostitutiviDomenicaEFestivo: '',
                orariSostitutiviPreFestivo: '',
                segnalareTimbratureFuoriFasce: true,
                lavoroStraordinarioAutorizzato: true,
                lavoroStraordinarioArrotondamento: 'titolare',
                lavoroStraordinarioArrotondamentoSulleFasceDaAutorizzare: false,
                profilosId: 0,
                compensazioneCompensazioneSelettiva: false,
                compensazioneCumuloAssenze: '',
                compensazioneCumuloStraordinario: '',
                compensazioneMassimale: '00:00',
                compensazioneSaldoPositivo: false,
                compensazioneFasceSeAssenza: false,
                compensazionePauseNonRispettate: false,
                compensazioneDeduzioneAdattivaTimbratureTipo: false,
                compensazioneSequenzeEu: '',
                compensazioneTimbratureFuoriFasciaElastica: '',
                compensazioneSpostaTimbraturaTipo: '',
                compensazioneDisattivaFasceDopoIndividuaTipo: false,
                compensazioneOrarioRigido: false,
                postElaborazioniCompensazioneAutomatica: false,
                postElaborazioniVociAutomatiche: false,
                postElaborazioniUsaTipoReali: true,
                oreTeoricheHHTeoriche: 'minime',
                oreTeoricheTipoGG: 'lavorativo',
                strategieIgnorareTimbratureOrfane: false,
                strategieTimbratureDiscriminazioneAutomatica: false,
                strategieGiustificativiRigidi: true,
                strategieGiustificativiFlex: false,
                strategieGiustificativiAssenzaTimbrature: true,
                OmissioneDescrizioneOrdiniServizio: false
            },
            {
                id: 3,
                orarioId: 3,
                codice: 'D01',
                breve: '',
                descrizione: 'Dirigenti',
                colore: '',
                tipologiaTipo: 'Elastico',
                tipologiaOreBase: '08:00',
                tipologiaOreMinime: '08:00',
                tipologiaGiornoDiSalvataggio: 'Entrata',
                timbratureDalle: '05:00',
                timbratureAlle: '',
                timbratureGiorniSuccessiviPerTimbratura: 2,
                timbratureTimbratureSuPiuGiorni: true,
                timbratureCausaliFuoriIntervallo: false,
                orariSostitutiviSabato: '',
                orariSostitutiviDomenicaEFestivo: '',
                orariSostitutiviPreFestivo: 'asd',
                segnalareTimbratureFuoriFasce: false,
                lavoroStraordinarioAutorizzato: true,
                lavoroStraordinarioArrotondamento: 'titolare',
                lavoroStraordinarioArrotondamentoSulleFasceDaAutorizzare: false,
                profilosId: 6,
                compensazioneCompensazioneSelettiva: false,
                compensazioneCumuloAssenze: '',
                compensazioneCumuloStraordinario: '',
                compensazioneMassimale: '03:00',
                compensazioneSaldoPositivo: false,
                compensazioneFasceSeAssenza: true,
                compensazionePauseNonRispettate: false,
                compensazioneDeduzioneAdattivaTimbratureTipo: true,
                compensazioneSequenzeEu: 'Solo Prima',
                compensazioneTimbratureFuoriFasciaElastica: 'Considerare',
                compensazioneSpostaTimbraturaTipo: 'Sino al limite della fascia',
                compensazioneDisattivaFasceDopoIndividuaTipo: true,
                compensazioneOrarioRigido: true,
                postElaborazioniCompensazioneAutomatica: false,
                postElaborazioniVociAutomatiche: false,
                postElaborazioniUsaTipoReali: true,
                oreTeoricheHHTeoriche: 'minime',
                oreTeoricheTipoGG: 'lavorativo',
                strategieIgnorareTimbratureOrfane: false,
                strategieTimbratureDiscriminazioneAutomatica: false,
                strategieGiustificativiRigidi: true,
                strategieGiustificativiFlex: false,
                strategieGiustificativiAssenzaTimbrature: true,
                OmissioneDescrizioneOrdiniServizio: false
            }
        ],
        fasceDellaGiornatas: [
            { id: 1, orarioId: 1, causale: 'Notturno 2', dalle: '00:00', alle: '04:59', priorita: 0 },
            { id: 2, orarioId: 1, causale: 'Notturno 2', dalle: '20:00', alle: '23:59', priorita: 0 },
            { id: 6, orarioId: 1, causale: 'Notturno 2', dalle: '00:00', alle: '04:59', priorita: 0 },
            { id: 7, orarioId: 1, causale: 'Notturno 2', dalle: '20:00', alle: '23:59', priorita: 0 },
            { id: 3, orarioId: 2, causale: 'Notturno 2', dalle: '20:00', alle: '23:59', priorita: 0 },
            { id: 4, orarioId: 3, causale: 'Notturno 2', dalle: '00:00', alle: '04:59', priorita: 0 },
            { id: 5, orarioId: 3, causale: 'Notturno 2', dalle: '20:00', alle: '23:59', priorita: 0 }
        ],
        fasceDelMonteOres: [
            { id: 1, orarioId: 1, causale: 'Maggior presenza', dalle: '00:00', alle: '07:59' },
            { id: 2, orarioId: 1, causale: 'Maggior presenza', dalle: '08:00', alle: '23:59' },
            { id: 3, orarioId: 2, causale: 'Maggior presenza', dalle: '00:00', alle: '06:59' },
            { id: 4, orarioId: 2, causale: 'Maggior presenza', dalle: '07:00', alle: '23:59' },
            { id: 5, orarioId: 3, causale: 'Maggior presenza', dalle: '00:00', alle: '07:59' },
            { id: 6, orarioId: 3, causale: 'Maggior presenza', dalle: '08:00', alle: '23:59' }
        ],
        timbratureTipos: [
            { id: 1, orarioId: 1, v: 'E', dalle: '03:55', alle: '04:05', gg: 0, timbratura: '04:00', tipo: 'virtuale' },
            { id: 2, orarioId: 1, v: 'U', dalle: '20:00', alle: '23:59', gg: 0, timbratura: '20:00', tipo: 'reale' },
            { id: 3, orarioId: 2, v: 'E', dalle: '03:55', alle: '04:05', gg: 0, timbratura: '04:00', tipo: 'virtuale' },
            { id: 4, orarioId: 2, v: 'U', dalle: '04:00', alle: '04:10', gg: 0, timbratura: '04:05', tipo: 'virtuale' },
            { id: 5, orarioId: 3, v: 'E', dalle: '04:55', alle: '05:05', gg: 0, timbratura: '05:00', tipo: 'virtuale' },
            { id: 6, orarioId: 3, v: 'U', dalle: '20:00', alle: '23:59', gg: 0, timbratura: '20:00', tipo: 'reale' }
        ],
        arrotondamentoTimbratures: [
            { id: 1, orarioId: 1, v: 'U', dalle: '00:00', dalle: '04:00', tipo: 'Difetto', ora: '', minuti: '30', plus_toll: '', cumula: '' },
            { id: 2, orarioId: 1, v: 'U', dalle: '20:00', dalle: '20:59', tipo: 'Ora Specificata', ora: '20:00', minuti: '', plus_toll: '', cumula: '' },
            { id: 3, orarioId: 1, v: 'U', dalle: '21:00', dalle: '23:59', tipo: 'Difetto', ora: '', minuti: '30', plus_toll: '', cumula: '' },
            { id: 4, orarioId: 3, v: 'U', dalle: '00:00', dalle: '05:00', tipo: 'Difetto', ora: '', minuti: '30', plus_toll: '', cumula: '' },
            { id: 5, orarioId: 3, v: 'U', dalle: '20:00', dalle: '20:59', tipo: 'Ora Specificata', ora: '20:00', minuti: '', plus_toll: '', cumula: '' },
            { id: 6, orarioId: 3, v: 'U', dalle: '21:00', dalle: '23:59', tipo: 'Difetto', ora: '', minuti: '30', plus_toll: '', cumula: '' }
        ],
        arrotondamentoStraordinarios: [
            { id: 1, orarioId: 1, dalle: '00:00', dalle: '00:59', tipo: 'Ora Specificata', ora: '00:00', minuti: '', toll: '' },
            { id: 2, orarioId: 1, dalle: '01:00', dalle: '23:59', tipo: 'Difetto', ora: '', minuti: '30', toll: '' },
            { id: 3, orarioId: 2, dalle: '00:00', dalle: '00:59', tipo: 'Ora Specificata', ora: '00:00', minuti: '', toll: '' },
            { id: 4, orarioId: 2, dalle: '01:00', dalle: '23:59', tipo: 'Difetto', ora: '', minuti: '30', toll: '' },
            { id: 5, orarioId: 3, dalle: '00:00', dalle: '23:59', tipo: 'Ora Specificata', ora: '00:00', minuti: '', toll: '' }
        ],
        pauses: [
            { id: 1, orarioId: 2, descrizione: 'Pausa Pranzo', dalle: '12:30', alle: '14:30', min: '00:45', max: '00:35', obbl: '', tipologia: 'Pausa Pranzo', voce: '', eccedenze: 'SOLO eccesso non lavorato', vocePerSegnalazione: '' }
        ],
        profilos: [
            { id: 1, nome: '00 - Quadri (prova)' },
            { id: 2, nome: 'G - Banca ore 100%' },
            { id: 3, nome: 'G - Banca ore 50%' },
            { id: 4, nome: 'G - No Straordinario' },
            { id: 5, nome: 'G - Straordinario 100%' },
            { id: 6, nome: 'O - Genova Giornaliero' },
            { id: 7, nome: 'O - Genova Riposo' },
            { id: 8, nome: 'O - Priolo Giornaliero' }
        ],
        vocis: [
            { id: 1, title: 'AARI Perm. Arca per riunioni' },
            { id: 2, title: 'AFEG Festività Goduta' },
            { id: 3, title: 'AI Assenza ingiustificata' },
            { id: 4, title: 'AIHH Assenza non giustificata' },
            { id: 5, title: 'ALOP Assenza giorno semifestivo' },
            { id: 6, title: 'ARIT Ritardo' },
            { id: 7, title: 'ASPG Aspettativa' },
            { id: 8, title: 'ASRE Assemb. Sind. retribuita' },
            { id: 9, title: 'FLEN Flessibilità negativa' },
            { id: 10, title: 'FLEP Flessibilità positiva' }
        ]
    }

});

export default dataProvider;